dist: xenial

language: node_js
node_js:
- "12"

services:
- xvfb

cache: yarn

env:
  global:
    # include $HOME/.local/bin for `aws`
    - PATH=$HOME/.local/bin:$PATH
    - CHROME_BIN=/usr/bin/google-chrome

before_install:
# set up awscli packages
- pip install --user awscli
- mkdir -p ~/shared
- if [ ! -z "$AWS_ACCESS_KEY_ID" ]; then aws s3 sync s3://nimiq-travis-builds/shared/$TRAVIS_BUILD_ID ~/shared --region eu-central-1; fi

install: true

jobs:
  include:
    - stage: build nimiq
      env: BUILD=true
      script:
        - npm install -g gulp
        - yarn
        - node_modules/.bin/gulp build
        - cp -r dist ~/shared
        - cp -r build ~/shared
        - tar czf node_modules.tar.gz node_modules
        - cp node_modules.tar.gz ~/shared
        - if [ ! -z "$AWS_ACCESS_KEY_ID" ]; then aws s3 sync ~/shared s3://nimiq-travis-builds/shared/$TRAVIS_BUILD_ID --region eu-central-1; fi
    - stage: build nimiq
      env: TO_TEST=ESLint
      script:
        - npm install -g gulp
        - yarn
        - node_modules/.bin/eslint src/main src/test *.js
        - node_modules/.bin/esdoc
    - stage: test
      env: TO_TEST=NodeJS
      script: ./travis-script.sh
#    - stage: test
#      os: osx
#      env: TO_TEST=Karma/Travis_CI/Safari
#      osx_image: xcode8.3
#      script: ./travis-script.sh
    - stage: test
      env: TO_TEST=Karma/SauceLabs/Edge_18
      addons:
        sauce_connect:
          username: nimiq
        jwt:
          secure: hoZJuHfZCCqD9umU2EbOlfcgLOhNjUJpkTHVVHny/CEjsonRcMO3+2dyASq1MspkhP+0au1KLXpKjvprkli8SMgNrrx35hyVVMw7p8Le0Flwmj+8oJkSqeUnJhfTRhcun0HB9lSILRpaQqW8eEgLQSlFf6uVQdk+rXcFPy/ZkM+PBZRwzlmdr1jtMQR0F+Iv/wz0ORy9GWA6hdpOqw8A0G3nnQqe9zZ8OdIXiVm/8ch8+hL4bGz6BoBC1kkhi1ia2Ne5KFSOEhz8P92S9K6IPSS+VqiZCZnOo/2alDQ4DniElskEliN1edhqOT4GCq29MfLZzV+xDqfRkcXwSbP0+t7QtHRG7ZW2cOHAPuyNlrdyWycVhB9Tp0khyHNxu3bK8HluCu0q2ZEpdZqQQvKPYJtaS/OmVszYFlj0RqDE1ZsrCCtpyawtqsvPrNPWcES3mro5P97884FFXX5Lou8QJkjm+rsHOxdHcONwz+b6TDRa4JQuubkglF9aeTHXgk0a6mpPcNDDEDNKQsaI99kAGxUbDSEDJ+Kc/t0ndZZ2L+OyrchgOajsRNopoUfopf3eOvGwGA6uQxGgQqLUueW2WNYI1Fh96RCYaZUCexh1hy24+LQLFzRYqxMQyMma11nSBsUudJoYk+ExI9GZgI8co7SxTxq0wh1wTFPv4Odcv50=
      script: ./travis-script.sh
#    - stage: test
#      env: TO_TEST=Karma/SauceLabs/Safari_11 EXCLUDE_MINER=true
#      addons:
#        sauce_connect:
#          username: nimiq
#        jwt:
#          secure: hoZJuHfZCCqD9umU2EbOlfcgLOhNjUJpkTHVVHny/CEjsonRcMO3+2dyASq1MspkhP+0au1KLXpKjvprkli8SMgNrrx35hyVVMw7p8Le0Flwmj+8oJkSqeUnJhfTRhcun0HB9lSILRpaQqW8eEgLQSlFf6uVQdk+rXcFPy/ZkM+PBZRwzlmdr1jtMQR0F+Iv/wz0ORy9GWA6hdpOqw8A0G3nnQqe9zZ8OdIXiVm/8ch8+hL4bGz6BoBC1kkhi1ia2Ne5KFSOEhz8P92S9K6IPSS+VqiZCZnOo/2alDQ4DniElskEliN1edhqOT4GCq29MfLZzV+xDqfRkcXwSbP0+t7QtHRG7ZW2cOHAPuyNlrdyWycVhB9Tp0khyHNxu3bK8HluCu0q2ZEpdZqQQvKPYJtaS/OmVszYFlj0RqDE1ZsrCCtpyawtqsvPrNPWcES3mro5P97884FFXX5Lou8QJkjm+rsHOxdHcONwz+b6TDRa4JQuubkglF9aeTHXgk0a6mpPcNDDEDNKQsaI99kAGxUbDSEDJ+Kc/t0ndZZ2L+OyrchgOajsRNopoUfopf3eOvGwGA6uQxGgQqLUueW2WNYI1Fh96RCYaZUCexh1hy24+LQLFzRYqxMQyMma11nSBsUudJoYk+ExI9GZgI8co7SxTxq0wh1wTFPv4Odcv50=
#      script: ./travis-script.sh
#    - stage: test
#      env: TO_TEST=Karma/SauceLabs/Safari_10.1 USE_BABEL=1
#      addons:
#        sauce_connect:
#          username: nimiq
#        jwt:
#          secure: hoZJuHfZCCqD9umU2EbOlfcgLOhNjUJpkTHVVHny/CEjsonRcMO3+2dyASq1MspkhP+0au1KLXpKjvprkli8SMgNrrx35hyVVMw7p8Le0Flwmj+8oJkSqeUnJhfTRhcun0HB9lSILRpaQqW8eEgLQSlFf6uVQdk+rXcFPy/ZkM+PBZRwzlmdr1jtMQR0F+Iv/wz0ORy9GWA6hdpOqw8A0G3nnQqe9zZ8OdIXiVm/8ch8+hL4bGz6BoBC1kkhi1ia2Ne5KFSOEhz8P92S9K6IPSS+VqiZCZnOo/2alDQ4DniElskEliN1edhqOT4GCq29MfLZzV+xDqfRkcXwSbP0+t7QtHRG7ZW2cOHAPuyNlrdyWycVhB9Tp0khyHNxu3bK8HluCu0q2ZEpdZqQQvKPYJtaS/OmVszYFlj0RqDE1ZsrCCtpyawtqsvPrNPWcES3mro5P97884FFXX5Lou8QJkjm+rsHOxdHcONwz+b6TDRa4JQuubkglF9aeTHXgk0a6mpPcNDDEDNKQsaI99kAGxUbDSEDJ+Kc/t0ndZZ2L+OyrchgOajsRNopoUfopf3eOvGwGA6uQxGgQqLUueW2WNYI1Fh96RCYaZUCexh1hy24+LQLFzRYqxMQyMma11nSBsUudJoYk+ExI9GZgI8co7SxTxq0wh1wTFPv4Odcv50=
#      script: ./travis-script.sh
    - stage: test
      env: TO_TEST=Karma/Travis_CI/Chrome_Stable
      addons:
        apt:
          sources:
          - google-chrome
          packages:
          - google-chrome-stable
      script: ./travis-script.sh
    - stage: test
      env: TO_TEST=Karma/Travis_CI/Chrome_Stable USE_BABEL=1
      addons:
        apt:
          sources:
          - google-chrome
          packages:
          - google-chrome-stable
      script: ./travis-script.sh
    - stage: test
      env: TO_TEST=Karma/Travis_CI/Chrome_Beta
      addons:
        apt:
          sources:
          - google-chrome
          packages:
          - google-chrome-beta
      script: ./travis-script.sh
    - stage: test
      env: TO_TEST=Karma/Travis_CI/Chrome_Module USE_ESM=1
      addons:
        apt:
          sources:
          - google-chrome
          packages:
          - google-chrome-beta
      script: ./travis-script.sh
#    - stage: test
#      env: TO_TEST=Karma/SauceLabs/Chrome_Old
#      addons:
#        sauce_connect:
#          username: nimiq
#        jwt:
#          secure: hoZJuHfZCCqD9umU2EbOlfcgLOhNjUJpkTHVVHny/CEjsonRcMO3+2dyASq1MspkhP+0au1KLXpKjvprkli8SMgNrrx35hyVVMw7p8Le0Flwmj+8oJkSqeUnJhfTRhcun0HB9lSILRpaQqW8eEgLQSlFf6uVQdk+rXcFPy/ZkM+PBZRwzlmdr1jtMQR0F+Iv/wz0ORy9GWA6hdpOqw8A0G3nnQqe9zZ8OdIXiVm/8ch8+hL4bGz6BoBC1kkhi1ia2Ne5KFSOEhz8P92S9K6IPSS+VqiZCZnOo/2alDQ4DniElskEliN1edhqOT4GCq29MfLZzV+xDqfRkcXwSbP0+t7QtHRG7ZW2cOHAPuyNlrdyWycVhB9Tp0khyHNxu3bK8HluCu0q2ZEpdZqQQvKPYJtaS/OmVszYFlj0RqDE1ZsrCCtpyawtqsvPrNPWcES3mro5P97884FFXX5Lou8QJkjm+rsHOxdHcONwz+b6TDRa4JQuubkglF9aeTHXgk0a6mpPcNDDEDNKQsaI99kAGxUbDSEDJ+Kc/t0ndZZ2L+OyrchgOajsRNopoUfopf3eOvGwGA6uQxGgQqLUueW2WNYI1Fh96RCYaZUCexh1hy24+LQLFzRYqxMQyMma11nSBsUudJoYk+ExI9GZgI8co7SxTxq0wh1wTFPv4Odcv50=
#      script: ./travis-script.sh
    - stage: test
      env: TO_TEST=Karma/Travis_CI/Firefox_Stable
      addons:
        firefox: latest
      script: ./travis-script.sh
    - stage: test
      env: TO_TEST=Karma/Travis_CI/Firefox_ESR
      addons:
        firefox: latest-esr
      script: ./travis-script.sh
    - stage: test
      env: TO_TEST=Karma/Travis_CI/Firefox_Beta
      addons:
        firefox: latest-beta
      script: ./travis-script.sh
    - stage: test
      env: TO_TEST=Karma/Travis_CI/Firefox_Module USE_ESM=1
      addons:
        firefox: latest-beta
      script: ./travis-script.sh
#    - stage: test
#      env: TO_TEST=Karma/Travis_CI/Firefox_56
#      addons:
#        firefox: 56
#      script: ./travis-script.sh
#    - stage: test
#      env: TO_TEST=Karma/Travis_CI/Firefox_55
#      addons:
#        firefox: 55
#      script: ./travis-script.sh

notifications:
  slack:
    secure: b823ZQHp4OzfRPrQYYQR2Iqe6cQnxV881VODT13YO8f8yZl4HLK/g7ngbCVnUXbbajUvNMaGOt+QM63rGVgIp9tcUNf+C1Hspo2E8dMiDSSWufSWBIJbfSkQ0LHBa7kuhBLqSeOBECc6aYtnjJVsc9VKqQ9Dy3q8iGao8Lztakq3IzLev7pV18StRdkvgbPReezQ7BQV5oPmaI1Vq60YRTlKJKNZAzapoW0jCzbGRoq0MvyMHDJQyW9qja++E+tSkgMvalA/WxtOj9rxD/ZWLwj6lcMMdLvm/ebixAVa/Fv/uE6kXTzFrm78SbvuAJeM8eLSl7K3DCpV8xC82kH5KwSaxDwpUofSotEgrZEa3yQFCmIe/8Yd170bzrWxbMUxSE8emhbMnWmh4dLNjPC1ouauT4eb3833dSbYUWBWwQpaEgmXE+gyEwyys2wX+e2t/fmpqC1OImehdotFVaIZEkk+eLW1913js+rL15ll/Lsj1j2esCEP8zxguo9MnWT8AC5nUhS7RHcQaAsOfSKo4ePOCFPH9skcnWaOoOz4K/Kk9yXLOCNjiK1EMgMLAzo7UxLrNVXWWoVxMRP4sDOuP+2qNwGNMQpuDVfaEQgj/HnvdsZf92bg5LWS/jgrvqtNqOZuiekZ4azk4JxIer2pdfwuP1t5vyzLtKMRNiY6xGU=
